import type {Conversation, ConversationSummary, StoredChatMessage, WorkingItem} from "../shared/conversation-types";
import {defaultGenerationSettings} from "../shared/generation-settings";
import type {ChatProfile} from "../shared/profile-types";
import type {ProviderProfile} from "../shared/provider-types";
import type {LocalCredential} from "./providers/local-providers";
import type {AgentCredentialMetadata, AgentProviderProfile} from "./providers/provider-agent-client";
import {embeddedModelsDevCatalog, embeddedModelsDevModelCount} from "./providers/models-dev-catalog";

export type ChatProvider = ProviderProfile & {modelDiscoveryError?: string};
export type ChatConfig = {providers: ChatProvider[]; profile: ChatProfile};
export type ServerChatConfig = {identityKey: string; profile: ChatProfile; capabilities?: {sync?: boolean}};
export type CachedChatBootstrap = {profile?: ChatProfile; config?: ChatConfig};
export type HashNavigationMode = "push" | "replace" | "none";

export function createInitialAppState() {
  const localProfile: ChatProfile = {username: "local", name: "本地用户", email: ""};
  return {
    config: null as ChatConfig | null,
    localCredentials: [] as LocalCredential[],
    conversations: [] as ConversationSummary[],
    conversation: null as Conversation | null,
    providerId: "",
    model: "",
    generationSettings: {...defaultGenerationSettings},
    recentModelKeys: [] as string[],
    historyOpen: window.matchMedia("(min-width: 681px)").matches,
    offline: false,
    loading: true,
    error: "",
    modelQuery: "",
    streaming: false,
    streamController: null as AbortController | null,
    workingItems: [] as WorkingItem[],
    activeDraftId: "",
    historyTree: window.localStorage.getItem("turnfold-history-tree") === "1",
    advancedActions: window.localStorage.getItem("turnfold-advanced-actions") === "1",
    identityKey: "",
    localProfile,
    backendUrl: "",
    backendActiveUrl: "",
    backendActiveTransport: "" as "" | "native" | "webdav",
    backendConnecting: false,
    backendError: "",
    backendPairingRequired: false,
    backendPairing: false,
    backendApprovalUrl: "",
    backendSavedGrant: false,
    backendActiveGrantToken: "",
    backendConnectionController: null as AbortController | null,
    backendPairingController: null as AbortController | null,
    backendPairingWindow: null as Window | null,
    backendSyncController: null as AbortController | null,
    webdavUrl: window.localStorage.getItem("turnfold-webdav-url") || "",
    webdavMode: (window.localStorage.getItem("turnfold-webdav-mode") || "turnfold") as "turnfold" | "basic" | "none",
    webdavUsername: window.localStorage.getItem("turnfold-webdav-username") || "turnfold",
    webdavPassword: "",
    webdavActiveRootUrl: "",
    webdavActiveMode: "" as "" | "turnfold" | "basic" | "none",
    webdavActiveUsername: "",
    webdavActivePassword: "",
    webdavGrantToken: "",
    webdavSavedGrant: false,
    webdavConnecting: false,
    webdavPairingRequired: false,
    webdavPairing: false,
    webdavApprovalUrl: "",
    webdavError: "",
    webdavController: null as AbortController | null,
    webdavPairingController: null as AbortController | null,
    webdavPairingWindow: null as Window | null,
    providerAgentUrl: "",
    providerAgentActiveUrl: "",
    providerAgentGrantToken: "",
    providerAgentSavedGrant: false,
    providerAgentConnecting: false,
    providerAgentPairingRequired: false,
    providerAgentPairing: false,
    providerAgentApprovalUrl: "",
    providerAgentError: "",
    providerAgentProfiles: [] as AgentProviderProfile[],
    providerAgentCredentials: [] as AgentCredentialMetadata[],
    providerAgentModeIds: new Set<string>(),
    providerAgentController: null as AbortController | null,
    providerAgentPairingController: null as AbortController | null,
    providerAgentPairingWindow: null as Window | null,
    providerAgentSaving: false,
    authenticated: false,
    syncing: false,
    syncRequested: false,
    initialFetchComplete: false,
    lastFetchAt: "",
    syncError: "",
    renderFrame: 0,
    settingsTimer: 0,
    syncTimer: 0,
    workingSaveTimers: new Map<string, number>(),
    messageGraph: [] as StoredChatMessage[],
    previewHeadId: "",
    queuedDraftId: "",
    importPanelOpen: false,
    importing: false,
    importStatus: "",
    importTitleTemplate: window.localStorage.getItem("turnfold-import-title-template") || "{title}",
    composerFullscreen: false,
    settingsOpen: false,
    providerEditorOpen: false,
    providerEditorId: "",
    providerEditorMode: "simple" as "simple" | "advanced",
    providerSetupKind: "catalog" as "catalog" | "detect",
    providerSetupUrl: "",
    providerSetupKey: "",
    providerSetupBusy: false,
    providerSetupError: "",
    providerSetupDetected: null as Omit<ProviderProfile, "createdAt" | "updatedAt"> | null,
    providerSetupController: null as AbortController | null,
    providerModelEditorOpen: false,
    providerModelProviderId: "",
    providerModelPresetId: "",
    providerModelQuery: "",
    modelsDevCatalog: embeddedModelsDevCatalog,
    modelsDevModelCount: embeddedModelsDevModelCount,
    modelsDevFetchedAt: "",
    modelsDevUpdating: false,
    modelsDevError: ""
  };
}

export type AppState = ReturnType<typeof createInitialAppState>;
